name: Build Windows Executable

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests python-dotenv
#create food_export.exe
    - name: Build executable with PyInstaller (Export)
      run: |
        pyinstaller --onefile --name Food_export export_foods.py
    
    - name: Upload executable as artifact (Export)
      uses: actions/upload-artifact@v4
      with:
        name: mealie_export_exe
        path: dist/Food_export.exe

#create food_import.exe
    - name: Build executable with PyInstaller (Import)
      run: |
        pyinstaller --onefile --name Food_import mealie_import.py
    
    - name: Upload executable as artifact (Import)
      uses: actions/upload-artifact@v4
      with:
        name: mealie_import_exe
        path: dist/Food_import.exe
      