name: Build Windows Executables and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
permissions:
  contents: write  # Required to create releases

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests python-dotenv

      # Export: Build, zip, and prepare for release
      - name: Build Export Executable
        run: pyinstaller --onefile --name Food_export export_foods.py

      - name: Create ZIP for Export
        run: |
          powershell Compress-Archive -Path dist/Food_export.exe, .env.example -DestinationPath dist/Food_export_package.zip

      # Import: Build, zip, and prepare for release
      - name: Build Import Executable
        run: pyinstaller --onefile --name Food_import mealie_import.py

      - name: Create ZIP for Import
        run: |
          powershell Compress-Archive -Path dist/Food_import.exe, .env.example -DestinationPath dist/Food_import_package.zip

      # Upload both ZIPs as release assets
      - name: Upload Export ZIP as Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Food_export_package.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Import ZIP as Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Food_import_package.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
